### ISSUE TITLE
Media uploads fail

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-quickstart#365] opened 2014-12-23 20:18 UTC
Media uploads fail with this error:

    “unknown.gif” has failed to upload due to an error
    The uploaded file could not be moved to uploads/2014/12.

Here's what the permissions look like:

    vagrant@vip:~$ ls -al /srv/www/wp-content/uploads/
    total 8
    drwxr-xr-x 1 vagrant vagrant  170 Dec 23 20:07 .
    drwxr-xr-x 1 vagrant vagrant  442 Dec 16 21:25 ..
    drwxr-xr-x 1 vagrant vagrant  510 Dec  1 15:54 2014
    drwxr-xr-x 1 vagrant vagrant  102 Oct  1 18:59 sites

    vagrant@vip:~$ ls -al /srv/www/wp-content/uploads/2014/
    total 8
    drwxr-xr-x 1 vagrant vagrant    510 Dec  1 15:54 .
    drwxr-xr-x 1 vagrant vagrant    170 Dec 23 20:07 ..
    drwxr-xr-x 1 vagrant vagrant 447780 Nov 17 17:04 01
    drwxr-xr-x 1 vagrant vagrant   3196 Nov 14 18:20 02
    drwxr-xr-x 1 vagrant vagrant 553792 Dec  8 19:09 03
    drwxr-xr-x 1 vagrant vagrant 115498 Dec  8 19:10 04
    drwxr-xr-x 1 vagrant vagrant 115192 Dec  8 19:11 05
    drwxr-xr-x 1 vagrant vagrant 130730 Dec  8 19:16 06
    drwxr-xr-x 1 vagrant vagrant  97206 Dec  1 20:40 07
    drwxr-xr-x 1 vagrant vagrant  32912 Dec  1 20:37 08
    drwxr-xr-x 1 vagrant vagrant  27846 Dec  8 19:21 09
    drwxr-xr-x 1 vagrant vagrant  34850 Dec  1 20:57 10
    drwxr-xr-x 1 vagrant vagrant  25636 Dec  8 19:23 11
    drwxr-xr-x 1 vagrant vagrant   2618 Dec  8 19:31 12

    vagrant@vip:~$ ls -al /srv/www/wp-content/uploads/2014/12
    total 63952
    drwxr-xr-x 1 vagrant vagrant    2618 Dec  8 19:31 .
    drwxr-xr-x 1 vagrant vagrant     510 Dec  1 15:54 ..

**Comment by mauteri** [comment] 2015-03-05 16:02
How is a fix to this looking? This issue is a blocker for a media component on our theme that we've been developing. Thx.

**Comment by gcerny** [comment] 2015-03-05 16:08
VIP, we're actually kind of dead in the water on this one.  We can't use Quickstart for what it's intended to do - act as a development environment that reliably emulates VIP Production - because we can't import files from our plugin's cloud repository, to local.   Can you please make this a priority?

**Comment by joshbetz** [comment] 2015-03-05 20:32
@mauteri @paulschreiber Is this locally in Vagrant or on a remote server?

**Comment by joshbetz** [comment] 2015-03-05 20:56
Chatted with Mike. Seems like this got fixed somehow. I'm going to close this for now because I think uploads are currently working -- I also can't reproduce any issues. Let me know if you see this again and I'll help look into it.

**Closed by joshbetz** 2015-03-05 20:56 UTC
