### ISSUE TITLE
PHP_CodeSniffer fails to install

### ISSUE THREAD

**Issue by salvo1404** [Automattic/vip-quickstart#475] opened 2015-11-03 03:21 UTC
When running vagrant up the first time, it gives this error:

"Download of "pear/PHP_CodeSniffer" succeeded, but it is not a valid package archive"

It looks like something is wrong with my ARCHIVE_TAR in PEAR.

![screen shot 2015-11-03 at 11 23 22 am](https://cloud.githubusercontent.com/assets/5450842/10900590/21a263ca-8236-11e5-989a-ad5e233c9aed.png)

**Comment by johnciacia** [comment] 2015-11-03 16:06
+1

**Comment by developdaly** [comment] 2015-11-05 17:21
Duplicate of #471?

**Comment by joshbetz** [comment] 2015-11-05 17:34
@developdaly Yes, I think so. Good call.

**Comment by jacklenox** [comment] 2015-11-13 10:16
I believe this is still a problem. Even trying to run `pear install PHP_CodeSniffer` after provisioning yields the following:

```
downloading PHP_CodeSniffer-2.3.4.tgz ...
Starting to download PHP_CodeSniffer-2.3.4.tgz (473,411 bytes)
............................................................................done: 473,411 bytes
could not extract the package.xml file from "/build/php5-q1fasi/php5-5.3.10/pear-build-download/PHP_CodeSniffer-2.3.4.tgz"
Download of "pear/PHP_CodeSniffer" succeeded, but it is not a valid package archive
Error: cannot download "pear/PHP_CodeSniffer"
Download failed
install failed
```

**Comment by philipjohn** [comment] 2015-11-13 10:16
In #471 PHPCS *is* installed, so they do appear to be separate issues

**Closed** 2015-11-18 16:35 UTC
