### ISSUE TITLE
really slow on macbook

### ISSUE THREAD

**Issue by showcasefloyd** [Automattic/vip-quickstart#410] opened 2015-03-19 20:59 UTC
Any tips to speed this up? I'm trying to work on a plug in, but it's painfully slow.

**Comment by joshbetz** [comment] 2015-03-19 21:00
Dupe of #372

**Closed by joshbetz** 2015-03-19 21:00 UTC

**Comment by westonruter** [comment] 2015-03-19 21:06
@showcasefloyd this NFS workaround is what me and my colleagues have been using to make the speed bearable: https://github.com/Automattic/vip-quickstart/issues/372#issuecomment-73650663

**Comment by showcasefloyd** [comment] 2015-03-19 21:13
I'm trying it now. But for some reason the vip.local is now coming up 404
