### ISSUE TITLE
Please enable Insert Embed on VIP Quickstart

### ISSUE THREAD

**Issue by davidosomething** [Automattic/vip-quickstart#388] opened 2015-02-11 20:40 UTC
The **Insert Embed** link is missing in the Add Media modal.

On actual VIP:
![VIP production](https://s3.amazonaws.com/uploads.hipchat.com/43240/289255/8BcACACxYwIfeXQ/productioninsertembed.jpg)

On VIP-Quickstart:
![VIP-Quickstart](http://content.screencast.com/users/davidosomething/folders/Jing/media/a3427b15-6750-4656-889d-7f42c8b5f73f/00000197.png)

How can we get it on our instance?

**Comment by joshbetz** [comment] 2015-02-11 20:41
Dupe of #142

**Closed by joshbetz** 2015-02-11 20:41 UTC
