### ISSUE TITLE
provisioning script changes ownership + permissions on shared folders

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-quickstart#486] opened 2015-12-26 03:07 UTC
The provisioning script currently changes ownership an permissions on shared folders. I have thousands of lines like this:

```
==> default: notice: /File[/srv/www/wp-content/themes/vip/espn-plugins/node_modules/es5-ext/array/#/remove.js]/group: group changed 'vagrant' to 'www-data'
==> default: notice: /File[/srv/www/wp-content/themes/vip/espn-plugins/node_modules/es5-ext/array/#/remove.js]/mode: mode changed '0644' to '0664'
==> default: notice: /File[/srv/www/wp-content/themes/vip/espn-plugins/node_modules/es5-ext/test/error]/owner: owner changed 'vagrant' to 'www-data'
```

Please exclude shared folders from the chown/chmod script.

**Comment by joshbetz** [comment] 2015-12-27 03:05
Dupe of #374

**Closed by joshbetz** 2015-12-27 03:05 UTC
