### ISSUE TITLE
Install PHPUnit from PHAR or Composer

### ISSUE THREAD

**Issue by johnciacia** [Automattic/vip-quickstart#371] opened 2015-01-08 22:23 UTC
When trying to run `phpunit` I receive the following error:

```
vagrant@vip:/vagrant/www/wp-tests$ phpunit
You have installed PHPUnit via PEAR. This installation method is no longer
supported and http://pear.phpunit.de/ will be shut down no later than
December, 31 2014.

Please read http://phpunit.de/manual/current/en/installation.html and
learn how to use PHPUnit from a PHAR or install it via Composer.

vagrant@vip:/vagrant/www/wp-tests$
```

**Comment by joshbetz** [comment] 2015-01-08 22:29
Yeah... :(

This is a dupe of #289.

**Closed by joshbetz** 2015-01-08 22:29 UTC

**Comment by westonruter** [comment] 2015-01-08 22:30
As a workaround, I've provided a script to my team to install PHPUnit via PHAR:

```bash
#!/bin/bash

set -e

if command -v phpunit >/dev/null 2>&1; then
	echo 'phpunit already installed, so aborting'
	exit
fi

if [ ! -e /usr/local/bin/ ]; then
	echo 'Fail: /usr/local/bin/ does not exist'
	exit 1
fi

sudo wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
sudo chmod +x /usr/local/bin/phpunit

phpunit --version
```
