### ISSUE TITLE
phpunit fails to install

### ISSUE THREAD

**Issue by sudar** [Automattic/vip-quickstart#378] opened 2015-02-02 05:41 UTC
When I run `vagrant up` on a fresh vip-quickstart I am getting the following error. Is there anyway to fix it and install phpunit?

```
==> default: err: /Stage[main]/Php::Phpunit/Package[pear.phpunit.de/PHPUnit]/ensure: change from absent to present failed: Execution of '/usr/bin/pear upgrade pear.phpunit.de/PHPUnit' returned 1: Attempting to discover channel "pear.phpunit.de"...
==> default: downloading End-of-Life-for-PEAR-Installation-Method ...
==> default: Starting to download End-of-Life-for-PEAR-Installation-Method (Unknown size)
==> default: ......done: 28,088 bytes
==> default: unknown channel "pear.phpunit.de" in "pear.phpunit.de/PHPUnit"
==> default: invalid package name/package file "pear.phpunit.de/PHPUnit"
==> default: upgrade failed
```

**Comment by westonruter** [comment] 2015-02-02 05:48
This is a duplicate of #289.

In the mean time, you can manually install PHPUnit via:

```bash
sudo wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
sudo chmod +x /usr/local/bin/phpunit
```

**Comment by sudar** [comment] 2015-02-02 06:31
@westonruter Thanks.

**Closed** 2015-02-02 13:55 UTC
