### ISSUE TITLE
Not seeing PHP warnings and notices 

### ISSUE THREAD

**Issue by keithwi** [Automattic/vip-quickstart#451] opened 2015-08-14 16:35 UTC
I recently got a fresh copy of quickstart and was making a WP plugin. I do see PHP errors but I don't see any warnings or notices. I did SSH into the virtual machine and changed the `error_reporting` to `E_ALL` but still no luck. Any clues?

**Comment by johnciacia** [comment] 2015-08-14 16:38
Duplicate of #404?

**Comment by keithwi** [comment] 2015-08-14 16:46
Yes it is. Thanks

**Comment by keithwi** [comment] 2015-08-14 17:02
Any fix for this other than editing the plugin? The suggested workaround doesnt work for me (https://gist.github.com/westonruter/187da1b14f0149243fd0)

**Comment by joshbetz** [comment] 2015-08-15 15:04
Let's track this in #404

**Closed by joshbetz** 2015-08-15 15:04 UTC
